// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPfNXydTt5d7snLOfehnxSYzpk_6SY2tY',
    appId: '1:501653414875:web:d2d747e4b57aaff8517dfe',
    messagingSenderId: '501653414875',
    projectId: 'e-waste-ffbe2',
    authDomain: 'e-waste-ffbe2.firebaseapp.com',
    storageBucket: 'e-waste-ffbe2.firebasestorage.app',
    measurementId: 'G-ZQCND66C3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMbIQkX14QYDnLePmcAFi8xAzkDhUp1-4',
    appId: '1:501653414875:android:ee4a8fb5724f4d7a517dfe',
    messagingSenderId: '501653414875',
    projectId: 'e-waste-ffbe2',
    storageBucket: 'e-waste-ffbe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKLi-QlnCwEDx2JYGVV_lFDO2iiEV1VY',
    appId: '1:501653414875:ios:f7b7542189d6e545517dfe',
    messagingSenderId: '501653414875',
    projectId: 'e-waste-ffbe2',
    storageBucket: 'e-waste-ffbe2.firebasestorage.app',
    iosBundleId: 'com.example.eWasteApp',
  );
}
